### ISSUE TITLE
3 scripts/tasks are broken; (perhaps because of that) the CI build is too simple

### ISSUE THREAD

**Issue by tripu** [Marak/faker.js#1018]
On a clean `master`:

**`jsdoc`:**

```
$ npx gulp jsdoc
[19:19:30] Using gulpfile faker.js/gulpfile.js
[19:19:30] Starting 'jsdoc'...
[19:19:30] 'jsdoc' errored after 11 ms
[19:19:30] Error: File not found with singular glob: faker.js/README.md (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (faker.js/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:482:12)
    at Glob._finish (faker.js/node_modules/glob/glob.js:197:8)
    at done (faker.js/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (faker.js/node_modules/glob/glob.js:688:12)
    at faker.js/node_modules/glob/glob.js:676:10
    at Glob._stat2 (faker.js/node_modules/glob/glob.js:772:12)
    at lstatcb_ (faker.js/node_modules/glob/glob.js:764:12)
```

(`npm run jsdoc` produces the same result)

**`coverage`:**

```
$ npm run coverage

> faker@5.1.0 coverage faker.js
> nyc report --reporter=text-lcov | coveralls

ENOENT: no such file or directory, scandir 'faker.js/.nyc_output'
[error] "2020-10-03T17:21:06.624Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2020-10-03T17:21:06.625Z"  'input: ' ''
[error] "2020-10-03T17:21:06.626Z"  'error from convertLcovToCoveralls'

faker.js/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Failed to parse string
(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! faker@5.1.0 coverage: `nyc report --reporter=text-lcov | coveralls`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the faker@5.1.0 coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2020-10-03T17_21_06_637Z-debug.log
```

**`lint`:**

```
$ npm run lint

> faker@5.1.0 lint faker.js
> jshint ./lib --config ./.jshintrc

lib/address.js: line 5, col 17, Unexpected space after 'Address'.
lib/address.js: line 6, col 3, Expected 'var' to have an indentation at 5 instead at 3.
lib/address.js: line 16, col 3, Expected 'this' to have an indentation at 5 instead at 3.
⋮
lib/vehicle.js: line 109, col 5, Expected 'description' to have an indentation at 9 instead at 5.
lib/vehicle.js: line 110, col 5, Expected 'sampleResults' to have an indentation at 9 instead at 5.
lib/vehicle.js: line 111, col 3, Expected '}' to have an indentation at 5 instead at 3.

60878 errors
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! faker@5.1.0 lint: `jshint ./lib --config ./.jshintrc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the faker@5.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     .npm/_logs/2020-10-03T17_21_51_952Z-debug.log
```

Perhaps because of these errors, [the builds on Travis](https://travis-ci.org/github/Marak/faker.js) do just `npm i` and `npm t`.

We should fix these scripts, and then run them all as part of CI!

**Comment by tripu** [comment]
:mega:  
**Anyone interested in fixing these scripts (and in ongoing development of Faker in general)**:  
one of these is already fixed on my own fork, and [the other two are planned](https://github.com/tripu/faker.js/issues?q=is%3Aissue+%22fix+npm+script%22).

* GitHub project: [`tripu/faker.js`](https://github.com/tripu/faker.js)
* Alternative npm package: [`phaker`](https://www.npmjs.com/package/phaker)
