### ISSUE TITLE
Tests failing from fresh fork?

### ISSUE THREAD

**Issue by marvinIsSacul** [Marak/faker.js#1265]
Hello,

I've just forked this repo and ran `yarn install & yarn test` and the tests error out with this:

```
20365 passing (1m)
  3 failing

  1) datatype.js
       bigInt
         Generate and compare two numbers of data type BigInt, with seeding:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 97951384819n
- 90780478341n
      + expected - actual

      -97951384819n
      +90780478341n
      
      at Context.<anonymous> (test/datatype.unit.js:300:14)
      at processImmediate (internal/timers.js:461:21)

  2) finance.js
       litecoinAddress()
         returns a random litecoin address:
     AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(litecoinAddress.match(/^[LM3][1-9a-km-zA-HJ-NP-Z]{25,32}$/))

      at Context.<anonymous> (test/finance.unit.js:282:18)
      at processImmediate (internal/timers.js:461:21)

  3) random.js
       number
         should return deterministic results when seeded with array - one element:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'Duane Kshlerin'
- 'Duane Kub'
          ^
      + expected - actual

      -Duane Kshlerin
      +Duane Kub
      
      at Context.<anonymous> (test/random.unit.js:37:14)
      at processImmediate (internal/timers.js:461:21)



error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bmenant** [comment]
Happened to me as well while making https://github.com/Marak/faker.js/pull/1262
