### ISSUE TITLE
Doesn't work in strict mode?

### ISSUE THREAD

**Issue by chasm** [Marak/faker.js#153]
```
/Users/.../Workspace/.../node_modules/faker/lib/locales/sk.js:2284
    "bs_noun": [
    ^^^^^^^^^
SyntaxError: Duplicate data property in object literal not allowed in strict mode
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/.../Workspace/.../node_modules/faker/lib/locales.js:25:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by tkoomzaaskz** [comment]
@chasm this has been fixed in dc119ecd7fa7dbe45c78254e921521ec8d0a15f5. Thank you for pointing it out.
