### ISSUE TITLE
Faker.fake - mustache parsing of parameters failing

### ISSUE THREAD

**Issue by proviral** [Marak/faker.js#349]
Version:
faker@3.0.1

Example:
{{lorem.words(1)}}

Stack Trace:
node_modules/faker/lib/fake.js:45
      throw new Error('Invalid method: ' + parts[0] + "." + parts[1]);
            ^
Error: Invalid method: lorem.words(1)
    at Faker.fake (node_modules/faker/lib/fake.js:45:13)
    at generateFakeData (test/test-reports-blockedRequestReport.js:71:21)
    at Object.<anonymous> (test/test-reports-blockedRequestReport.js:101:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/lib/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/lib/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/usr/lib/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/usr/lib/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by proviral** [comment]
I pull the fake function locally and it works

**Comment by Marak** [comment]
Will prepare a new release from MASTER soon.

**Comment by greyhwndz** [comment]
@Marak, the library is great and I am enjoying it's use! :+1:
Is there a plan to support the following?
`faker.fake('{{list.random(name.firstName, name.lastName)}}_{{random.number({min:200, max:9999})}}@test.com'`
It would be great to do something like that :)

**Comment by DanielJoyce** [comment]
Yeah, object style parameters in mustache templates are not processed properly. Failing for me.

```
faker.fake("{{random.number({'max':24})}}")
"NaN"
```

**Comment by Marak** [comment]
Resolved in `master`. New release coming soon.
