### ISSUE TITLE
Path must be a string

### ISSUE THREAD

**Issue by filipeinacio** [Marak/faker.js#441]
Hi,

I need some help. I'm trying to contribute, and to do so, i'm trying to build the project.

I'm getting this error:
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:695:5)
....

Can someone help me?

node: v7.2.0
npm: 3.10.9
gulp -v
[23:41:18] CLI version 3.9.1
[23:41:18] Local version 3.8.8

**Comment by filipeinacio** [comment]
Solved on windows.

In the method "self.lookupPackage(row.file,", row.file was undefined, i had to change to row.id.
