### ISSUE TITLE
faker.internet.password(patter) throws "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by Viterzgir666** [Marak/faker.js#826]
Hi! 

Using "faker": "^4.1.0"
Using for automated tests where I generated password with `faker.internet.password()` but sometimes it generated a password with symbols only or symbols + numbers, but our system requires 3 different types of characters so I decided to add patter. 
```
const passwordPattern = /(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/
faker.internet.password(passwordPattern)
```

When I run tests, browser spawns but then I get the error 
```
ERROR @wdio/runner: RangeError: Maximum call stack size exceeded
    at RegExp.get source [as source] (<anonymous>)
    at RegExp.toString (<anonymous>)
    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:362:26)
    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)
    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)
    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)
    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)
    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)
    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)
    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)
0-1 worker error { name: 'RangeError',
  message: 'Maximum call stack size exceeded',
  stack:
   'RangeError: Maximum call stack size exceeded\n    at RegExp.get source [as source] (<anonymous>)\n    at RegExp.toString (<anonymous>)\n    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:362:26)\n    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)\n    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)\n    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)\n    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)\n    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)\n    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)\n    at _password (/Users/me/WebstormProjects/project/gui-tests/node_modules/faker/lib/internet.js:380:15)' }
```

**Comment by samir-araujo** [comment]
I have very limited knowledge with RegEx, so I don't know if that is really the problem, but reading the code of [`internet.password` function](https://github.com/Marak/faker.js/blob/master/lib/internet.js#L415), seems like the RegEx pattern is matched against each character individually.

As your RegEx always returns a false when matched against the single digit, it creates an infinite loop, thus throwing this error.

Maybe a better option would be using a lib that generate random string based on a RegEx like [RandExp](https://github.com/fent/randexp.js).

I have created a example with your RegEx that seems to work: https://codesandbox.io/s/ancient-field-k78p8

**Comment by chrys-exaucet** [comment]
I'm facing the exact same issue. Any update beside the suggested library?

**Comment by diptic21-wellsky** [comment]
> 

which cypress version you are using ?

**Comment by exaucae** [comment]
@diptic21-wellsky,  none. I never mentioned Cypress.

**Comment by rleachpear** [comment]
Also seeing this in Node:
```
> faker.internet.password(8, false, /[a-z][A-Z]/)
Uncaught RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at _password (/Users/ryanleach/src/peartherapeutics/pear-api-facade-library/node_modules/faker/lib/internet.js:416:17)
    at _password (/Users/ryanleach/src/peartherapeutics/pear-api-facade-library/node_modules/faker/lib/internet.js:417:16)
    at _password (/Users/ryanleach/src/peartherapeutics/pear-api-facade-library/node_modules/faker/lib/internet.js:417:16)
    at _password (/Users/ryanleach/src/peartherapeutics/pear-api-facade-library/node_modules/faker/lib/internet.js:417:16)
    at _password (/Users/ryanleach/src/peartherapeutics/pear-api-facade-library/node_modules/faker/lib/internet.js:417:16)
    at _password (/Users/ryanleach/src/peartherapeutics/pear-api-facade-library/node_modules/faker/lib/internet.js:417:16)
    at _password (/Users/ryanleach/src/peartherapeutics/pear-api-facade-library/node_modules/faker/lib/internet.js:417:16)
    at _password (/Users/ryanleach/src/peartherapeutics/pear-api-facade-library/node_modules/faker/lib/internet.js:417:16)
    at _password (/Users/ryanleach/src/peartherapeutics/pear-api-facade-library/node_modules/faker/lib/internet.js:417:16)
```
