### ISSUE TITLE
Build doesn't run locally

### ISSUE THREAD

**Issue by mastermatt** [Marak/faker.js#865]
Follow-up to https://github.com/Marak/faker.js/pull/864#issuecomment-575226583 @Marak 

My understanding from CONTRIBUTING.md is that before contributors open a pull-request, they should update contents inside the `lib` directory and then run `npm run build`.
However, after making the changes for https://github.com/Marak/faker.js/pull/864, `npm run build` not only failed with `Error: EMFILE: too many open files`, but it also make many changes to unrelated docs that lead me to believe the build has not successfully run and updated master in awhile. 

``` 
~/src/faker: git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
~/src/faker: node --version
v10.16.3
~/src/faker: npm run build

> faker@4.1.0 build /Users/mwilson/src/faker
> cd build && ../node_modules/.bin/gulp && cd ../

[10:21:39] Using gulpfile ~/src/faker/build/gulpfile.js
[10:21:39] Starting 'documentation'...
[10:21:39] Starting 'jsdoc'...
[10:21:39] Starting 'nodeLocalRequires'...
[10:21:39] Finished 'nodeLocalRequires' after 14 ms
[10:21:39] Starting 'browser-package'...
[10:21:39] Starting 'gh-pages'...
[10:21:39] Starting 'azTask'...
[10:21:39] Starting 'arTask'...
[10:21:39] Starting 'czTask'...
[10:21:39] Starting 'deTask'...
[10:21:39] Starting 'de_ATTask'...
[10:21:39] Starting 'de_CHTask'...
[10:21:39] Starting 'enTask'...
[10:21:39] Starting 'en_AUTask'...
[10:21:39] Starting 'en_BORKTask'...
[10:21:39] Starting 'en_CATask'...
[10:21:39] Starting 'en_GBTask'...
[10:21:39] Starting 'en_IETask'...
[10:21:39] Starting 'en_INDTask'...
[10:21:39] Starting 'en_USTask'...
[10:21:39] Starting 'en_ZATask'...
[10:21:39] Starting 'en_au_ockerTask'...
[10:21:39] Starting 'esTask'...
[10:21:39] Starting 'es_MXTask'...
[10:21:39] Starting 'faTask'...
[10:21:39] Starting 'frTask'...
[10:21:39] Starting 'fr_CATask'...
[10:21:39] Starting 'fr_CHTask'...
[10:21:39] Starting 'geTask'...
[10:21:39] Starting 'id_IDTask'...
[10:21:39] Starting 'itTask'...
[10:21:39] Starting 'jaTask'...
[10:21:39] Starting 'koTask'...
[10:21:39] Starting 'nb_NOTask'...
[10:21:39] Starting 'nepTask'...
[10:21:39] Starting 'nl_BETask'...
[10:21:39] Starting 'nlTask'...
[10:21:39] Starting 'plTask'...
[10:21:39] Starting 'pt_BRTask'...
[10:21:39] Starting 'pt_PTTask'...
[10:21:39] Starting 'roTask'...
[10:21:39] Starting 'ruTask'...
[10:21:39] Starting 'skTask'...
[10:21:39] Starting 'svTask'...
[10:21:39] Starting 'trTask'...
[10:21:39] Starting 'ukTask'...
[10:21:39] Starting 'viTask'...
[10:21:39] Starting 'zh_CNTask'...
[10:21:39] Starting 'zh_TWTask'...
[10:21:39] Finished 'documentation' after 239 ms
[10:21:40] Documented 23 files!
[10:21:41] Finished 'jsdoc' after 2.01 s
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open '/Users/mwilson/src/faker/package.json'
Emitted 'error' event at:
    at Transform.onerror (/Users/mwilson/src/faker/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at Transform.emit (events.js:198:13)
    at BufferList._callback (/Users/mwilson/src/faker/node_modules/vinyl-transform/index.js:29:32)
    at BufferList.<anonymous> (/Users/mwilson/src/faker/node_modules/bl/bl.js:16:14)
    at Labeled.emit (events.js:198:13)
    at Labeled.<anonymous> (/Users/mwilson/src/faker/node_modules/stream-splicer/index.js:133:18)
    at Labeled.emit (events.js:198:13)
    at Deps.<anonymous> (/Users/mwilson/src/faker/node_modules/stream-splicer/index.js:133:18)
    at Deps.emit (events.js:198:13)
    at /Users/mwilson/src/faker/node_modules/module-deps/index.js:345:30
    at onresolve (/Users/mwilson/src/faker/node_modules/module-deps/index.js:161:25)
    at /Users/mwilson/src/faker/node_modules/browserify/index.js:334:13
    at /Users/mwilson/src/faker/node_modules/browser-resolve/index.js:238:20
    at ReadFileContext.callback (/Users/mwilson/src/faker/node_modules/browser-resolve/index.js:106:24)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! faker@4.1.0 build: `cd build && ../node_modules/.bin/gulp && cd ../`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the faker@4.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mwilson/.npm/_logs/2020-01-16T17_21_56_050Z-debug.log
~/src/faker: git diff --stat
 Readme.md                        |   133 +-
 build/build/faker.js             | 21986 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------
 build/build/faker.min.js         |    46 +-
 doc/faker.address.html           |   921 ++++++++-
 doc/faker.commerce.html          |    13 +-
 doc/faker.company.html           |    13 +-
 doc/faker.database.html          |    13 +-
 doc/faker.date.html              |   191 +-
 doc/faker.finance.html           |   375 +++-
 doc/faker.hacker.html            |    13 +-
 doc/faker.helpers.html           |   449 +++-
 doc/faker.html                   |    26 +-
 doc/faker.image.html             |   123 +-
 doc/faker.internet.html          |    65 +-
 doc/faker.lorem.html             |    13 +-
 doc/faker.name.html              |    91 +-
 doc/faker.phone.html             |    13 +-
 doc/faker.random.html            |   585 +++++-
 doc/faker.system.html            |    17 +-
 doc/index.html                   |   213 +-
 doc/namespaces.list.html         |    22 +-
 doc/quicksearch.html             |     2 +-
 examples/browser/js/faker.js     | 21986 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------
 examples/browser/js/faker.min.js |    46 +-
 locale/nl_BE.js                  |     4 +-
 25 files changed, 36516 insertions(+), 10843 deletions(-)

~/src/faker: git diff --name-only --diff-filter=A HEAD
doc/faker.git.html
doc/faker.unique.html
doc/faker.vehicle.html
doc/global.html
locale/ar.js
locale/pt_PT.js
locale/ro.js
```
Notice the new doc html files: git, unique, vehicle, and global.

**Comment by Marak** [comment]
Thanks for letting us know about this. I can help.

First, we can prove that the build does actually work in the CI environment if we look at https://travis-ci.org/Marak/faker.js/builds/638027047?utm_source=github_status&utm_medium=notification

Second, we can google this error message `Error: EMFILE: too many open files`. I can guess your system needs increase of max open files ( file descriptors ). I think I had to do the same thing on my system a while back. Exact instructions will vary based on your operating system.

**Comment by Marak** [comment]
Hrmm, it occurs to me now that the CI won't actually run the build script? Could be nice to add that in the tests.

Regardless, I still think upping `open files` will fix the issue locally. We should document this.

**Comment by mastermatt** [comment]
I was able to get the script to run locally using some shenanigans, but then it tries to publish to gh-pages. So are contributors not suppose to run that script? Are PRs suppose to include build, docs, etc? It seems like they should be be removed from the repo and just included in the published pkg.

According to the footer of http://marak.github.io/faker.js, the docs haven't been updated since  2017-02-21.

**Comment by Marak** [comment]
PRs are not suppose to include updated builds or docs.

**Comment by Marak** [comment]
In the future, it would be nice for other users if you posted the solution you found for your initial problem instead of specifying the solution of the issue was `"using some shenanigans"`.

**Comment by mastermatt** [comment]
I specifically didn't want to list out how I got it working. I tried several things, brew installed watchman etc, however in the end, it seemed that running `sudo npm run build` was what got around the error. Since I don't condone using sudo in this case and I didn't want to explore the error more, I left out the details.

**Comment by Marak** [comment]
Appreciate the additional information. Thank you!
